const translationsEn = {
  homeLink: 'Home',
  shopLink: 'Shop',
  plantLink: 'Books',
  walksMade: 'WalksMade',
  loginBtn: 'Login',
  allPlants: 'All Plants',
  newArrivals: 'New Arrivals',
  sale: 'Sale',
  shopNow: 'SHOP NOW',
  myaccount: 'My Account',
  ourstores: 'Our stores',
  contactuc: 'Contact us',
  carrer: 'Career',
  helpguide: 'Help & Guide',
  helpcenter: 'Help Center ',
  howtobuy: 'How to Buy',
  shippingdelivery: 'Shipping & Delivery',
  productpolicy: 'Product Policy',
  about:
    "Bobur (taxallusi; full name Zahiriddin Muhammad ibn Umarshayx Mirzo; February 14, 1483 – December 26, 1530) was a prominent representative of Uzbek literature, a poet, historian, geographer, statesman, skilled military leader, founder of the Baburid dynasty, and a descendant of Timur. He served as the heir to Amir Temur. Bobur was one of the great personalities of his time, and his poems and quatrains are still widely read and appreciated today. He had six wives: Bibi Muboraka, Mohimbegim, Zaynab Sulton Begim, Oysha Sulton Begim, Maʼsuma Sulton Begim, and Soliha Sulton Begim. His father, Umarshayx Mirzo, was the ruler of Fergana Province, and his mother, Qutlugʻ Nigorxonim, was the daughter of Yunusxon, the ruler of Tashkent. Bobur's paternal grandmother was from the Moghulistan region. Bobur's father, Umarshayx Mirzo, was a ruler in Fergana, while his mother Qutlugʻ Nigorxonim was a learned and virtuous woman. Bobur took charge of the government with her support, and she actively assisted him in matters of governance and in military campaigns. Umarshayx Mirzo's court was located within the city walls of Andijon, and he spent his early years there. Bobur conducted his military campaigns in the Sirdaryo region and held the remaining months of the year in Andijon.Bobur, like all Timurid princes, received a special education under the guidance of distinguished scholars and mentors. He studied military science, Islamic jurisprudence, and various languages, including Arabic. He extensively studied historical and literary works, showing a keen interest in science, theology, and jurisprudence. Due to his courage and bravery, he earned the title Bobur (meaning tiger or lion) from his youth.Bobur's youth was spent in Andijon, where he received his early education. His father took him on expeditions and battles, allowing him to gain practical experience in warfare. Bobur showed interest in intellectual pursuits and regularly engaged in scholarly discussions with notable scholars and thinkers. His upbringing and bravery earned him the nickname 'Bobur' (meaning courageous or lion-hearted). After his father's death, Bobur faced internal conflicts and external threats but ultimately established himself as the ruler, assuming the title of Babur Shah in June 1494.",
  jang1:
    "The struggle for the Movarounnahr throne Portrait of Babur, 17th century. At the end of the 15th century, Movarounnahr was divided into many provinces, which became almost independent, headed by conflicting Timurid princes or wealthy nobles. The struggle for the Movarounnahr throne was in full swing, various political conspiracies were being organized. On top of that, several beks and governors subordinate to Umarshaikh Mirza refused to obey the young ruler (Babur). Some of them support Babur's brothers, some claim independence , others are opponents of Babur, others join their uncles and uncles and come to the point of losing him physically. In the first 2-3 years of Babur's reign, Babur, who repelled the attacks of his uncle and uncle, Sultan Ahmed Mirza, and Sultan Mahmud Khan, implemented important measures such as strengthening his position, improving relations with governors and officials, bringing order to the army, and establishing discipline in state affairs. Babur's initial political goal was to capture the strategically and geographically important Samarkand , the capital of Amir Temur's state , and to preserve and strengthen a strong state centered in Movarunnahr and restore Amir Temur's kingdom.",
  jang2:
    "Babur's recapture of Andijan Babur's accession to the throne, 1495At this time, in a short time, the third ruler came to the throne of Samarkand . After the death of Sultan Ahmad Mirza ( July 1494 ) , Sultan Mahmud Mirza did not rule the state in Samarkand for more than 5-6 months - he died at the age of 43 after a short illness . His son Boysungur, who is the governor of Bukhara , will take his place. In 1495-1496, Babur made two unsuccessful campaigns to Samarkand. In the fall of 1497, he captured a number of places around Samarkand, and after a 7-month siege of Samarkand, Boysungur fled to Kunduz . The city was going through extremely difficult times due to the siege . It was difficult to find even grain . Babur faced great difficulties in providing his army . Some of the workers flee to Andijan and Akhsi. After that, some of the begs who remained in Andijan turned their backs on Babur and joined his brother Jahangir Mirza . Babur, who was unhappy with Andijan and suffered from economic difficulties , and experienced a serious illness at the same time, decided to leave Samarkand after ruling it for a hundred days . Babur's attempt to recapture Andijan with the support of his uncle Mahmudkhan , governor of Tashkent , was unsuccessful. This failure had a negative impact on Babur's army, and most of the beks and navkars (700-800 people) left Babur. After staying in Khojand for some time, Babur, who remained with his loyal men (200-300), came to Tashkent to meet Mahmud Khan and began to make a plan to recapture Andijan . After a certain period of time, Babur returned to Khojand, and soon after, he captured Margilon and oversaw the capture of Andijan. Finally, after 2 years ( June 1498 ), he regained it. Babur made peace with his brother Jahangir Mirza and left the regions on the Akhsi side of the Khojand water... at his disposal, and took the Andijan side regions under his control.",
  jang3:
    "Efforts made to conquer Samarkand Babur in Samarkand When the wars between Timurids intensified, Shaibani Khan began to conquer Movarounnahr . In 1499, he traveled through Jizzakh and Samarkand to Karshi and Shahrisabz , returning to Dashti Kipchak with a large booty . Shortly after that, Shaibani Khan , who returned to Movarounnahr with a large force, captured Bukhara and Karakol ( 1499 ), Sultan Ali Mirza treacherously surrendered Samarkand to Shaibani Khan without a fight ( 1500 ), but a certain part of the city's population and nobles supported the restoration of Timurid rule. They sent a letter to the governor of Ferghana , Babur , and invited him to occupy Samarkand. When Babur arrived in Samarkand with his army (240 people) in the late fall of 1500 , the people greeted him and opened the city gates . 600 soldiers left by Shaibani Khan to protect the city will be destroyed. Shaibani Khan retreats to Bukhara. In a short time , Babur's governorship was recognized in all districts of Samarkand, in the cities of Karshi and Guzor , but the city ran out of food supplies and famine began. When Shaibani Khan learned about this, he gathered a lot of strength and started marching to Samarkand again. In April 1501, Babur's troops were defeated in a battle near the village of Saripul on the Zarafshan River. Babur retreats to Samarkand. The city was besieged again for four months. The inhabitants of the besieged city were starving, and in the second half of 1501, Babur left Samarkand out of desperation and went to Tashkent to meet Mahmud Khan.",
  jang4:
    'Occupy India . Babur in India, 1527. By the spring of 1519, Babur began to implement plans to conquer India and organized several campaigns over the next 5-6 years. Uzbek sultans Sultan Hamza, Sultan Mahdi, Sultan Mamaq are in the reception of Babur Finally, in 1525, Babur started marching to India with 12,000 troops. In April 1526, in Panipat , he crushed the army of 100,000 people of his main opponent, the Sultan of Delhi, Ibrahim Lodi, with 12,000 soldiers and captured Delhi . Soon after, he won over the second largest Indian general , Rano Sango , and subjugated the northern part of India up to Bengal . Having chosen Agra as his capital, Babur began large-scale construction and improvement works. In this way, Babur founded the powerful Babur dynasty , which ruled India for about three and a half centuries . Contribution to the development of India  Babur did many social good deeds in India as well as in Afghanistan and had a significant impact on the development of the country. He put an end to disunity and disorganization, mutual internal conflicts and massacres, unified the regions, paid great attention to strengthening the centralized state and beautifying the country, developing science, crafts and agriculture. He led the construction works. He is considered the author of various ghazals.',
  jang5:
    'Capture of Kabul . Coin minted by Babur in Kabul, 1507-1508 Babur warriors, 1520s Babur with his army of 200-300 men crossed the Hissar mountains to Afghanistan and took advantage of the internal conflicts there to capture Ghazni and Kabul. After taking over Kabul, Babur began to build an independent state, organized the army, and established strict internal discipline. Babur treated Kabul and Afghanistan in general as his own country, started construction, beautification, development of trade and agriculture. He established camps such as Bogi Shakhroro , Bogi Jahanoro , Ortabog , Bogi Wafa and Bogi Babur . He made the Bolo Hissar fortress inside the city his residence, renovated it, built new buildings and lived in this fortress with his family. His children Humayun , Gulbadanbegim , Komron and Hindol were born here. Kutlug Nigorkhanim Mirzo Ulugbek, who died in the spring of 1506, will be buried in the Bogi Navrozi built here . Babur was active in Afghanistan not as a conqueror, but as an active ruler who devoted his life to the welfare and prosperity of this country, and worked justly and wisely for its interests. According to his practical activities in Afghanistan, Babur gained a great reputation as a powerful head of state and a victorious general in the whole of Khurasan and Mowarunnahr, and the political life in the region rose to prominence. The fact that Sultan Husayn Boykara specially invited Babur, among all the Timurid rulers, to the consultation meeting in the matter of taking joint measures against the increasing Shaybanite march, is a proof of such a high influence. Babur went to Herat on this offer. Despite the sudden death of Husayn Boykara (1506), he went to Herat and held talks with Timurid rulers. The plans of the Timurid rulers to unite and block the forces of Shaibani Khan will not be realized, and soon they will be defeated one after another and the kingdom will be completely lost. At the beginning of 1507 , Babur began to march to India, but this attempt failed and he returned to the capital Kabul.',
  lorem1: '1. The struggle for the throne of Movarounnahr  👇',
  lorem2: '2. Babur`s recapture of Andijan  👇',
  lorem3: '3. Efforts to conquer Samarkand  👇',
  lorem4: '4. Occupation of India  👇',
  lorem5: '5. Capture of Kabul  👇',
}

export default translationsEn
