const translationsUz = {
  homeLink: 'Asosiy',
  shopLink: 'Xarid',
  plantLink: 'Kitoblar',
  walksMade: 'Yurishlari',
  loginBtn: 'Kirish',
  allPlants: 'Barchasi',
  newArrivals: 'Yangilari',
  sale: 'Aksiyada',
  shopNow: 'Xarid qilish',
  myaccount: 'Mening Hisobim',
  ourstores: 'Bizning do`konlarimiz',
  contactuc: 'Biz bilan bog`laning',
  carrer: 'Karyera',
  helpguide: 'Yordam va qoʻllanma',
  helpcenter: 'Yordam markazi',
  howtobuy: 'Qanday qilib sotib olish mumkin',
  shippingdelivery: 'Yetkazib berish va yetkazib berish',
  productpolicy: 'Mahsulot siyosati',
  about:
    'Bobur (taxallusi; toʻliq ismi Zahiriddin Muhammad ibn Umarshayx Mirzo; 1483-yil 14-fevral – 1530-yil 26-dekabr) — oʻzbek mumtoz adabiyotining yirik vakili, shoir, tarixchi, geograf, davlat arbobi, isteʼdodli  sarkarda, boburiylar sulolasi asoschisi, temuriy shoh boʻlgan. Amir Temurning pannevarasi boʻlgan.[2] Bobur  oʻz davrining buyuk shaxslaridan biri edi. Uning sheʼrlari,ruboiylari oʻz vaqtida va hozir ham sevib  oʻqilmoqda. 6 ta xotini boʻlgan. Bibi Muboraka, Mohimbegim, Zaynab Sulton Begim, Oysha Sulton Begim, MaʼsumaSulton Begim va Soliha Sulton Begim. Boburning otasi – Umarshayx Mirzo Fargʻona viloyati hokimi, onasi –Qutlugʻ Nigorxonim Moʻgʻuliston xoni va Toshkent hokimi Yunusxonning qizi edi. Bobur ota tomondan AmirTemurning uchinchi oʻgʻli Mironshoh Mirzo naslidan boʻlsa, ona tomonidan Tugʻluq Temurxonning oʻgʻli XizrXo‘jaxon naslidan edi uning yettinchi avlodi edi. Boburning onasi oʻqimishli boʻlgan va oqila ayol boʻlib,Boburga hokimiyatni boshqarish ishlarida faol koʻmak bergan, harbiy yurishlarida unga hamrohlik qilgan.Umarshayx Mirzo xonadoni poytaxt Andijonning arki ichida yashar edi. Hokim yoz oylari Sirdaryo boʻyida,Axsida, yilning qolgan faslini Andijonda oʻtkazardi. Boburning yoshligi Andijonda oʻtgan. Bobur barcha temuriyshahzodalar kabi maxsus tarbiyachilar, yirik fozil-u ulamolar ustozligida harbiy taʼlim, fiqh ilmi, arab vafors tillarini oʻrganadi, koʻplab tarixiy va adabiy asarlar mutolaa qiladi, ilm-fanga, sheʼriyatga qiziqaboshlaydi. Dovyurakligi va jasurligi uchun u yoshligidan „Bobur“ („Sher“) laqabini oladi. Bobur otasi yoʻlidanborib, mashhur soʻfiy – Xoja Ahrorga ixlos qoʻyadi va uning tariqati ruhida voyaga yetadi, umrining oxirigaqadar shu eʼtiqodga sodiq qoladi. Keyinchalik, „Boburnoma“ asarida Bobur Xoja Ahror ruhi bir necha bor unimuqarrar halokatdan, xastalik va chorasizlikdan xalos etganini, eng ogʻir sharoitlarda rahnamolik qilganliginitaʼkidlaydi. Otasi Axsida bevaqt, 39 yoshida fojiali halok boʻlgach, oilaning katta farzandi, 12 yoshli Boburvaliahd sifatida taxtga oʻtiradi (1494-yil iyun)',
  jang1:
    'MOVOROUNNAHR TAXTI UCHUN KURASH . Bobur portreti, XVII asr.Movarounnahr XV asr oxirida oʻzaro nizolashayotgan temuriy shahzodalar yoki mulkdor zodagonlar boshchilik qilib turgan, deyarli mustaqil boʻlib olgan koʻpdan koʻp viloyatlarga parchalanib ketgan edi. Movarounnahr taxti uchun kurash avjga chiqqan, turli siyosiy fitnalar uyushtirilmoqda edi. Buning ustiga Umarshayx Mirzoga tobe bir necha bek va hokimlar yosh hukmdorga (Boburga) boʻysunishdan bosh tortadilar. Ularning ayrimlari Boburning ukalarini yoqlasa, baʼzilari mustaqillik daʼvosini qiladi, yana boshqa birlari Boburga raqib, boshqalari amaki, togʻalariga qoʻshilib, uni jismonan yoʻqotish payiga tushadi. Oʻz amakisi va togʻasi boʻlmish Sulton Ahmad Mirzo bilan Sulton Mahmudxon xurujlarini daf qilgan Bobur hukmronligining dastlabki 2—3-yilida mavqeini mustahkamlash, bek va amaldorlar bilan oʻzaro munosabatni yaxshilash, qoʻshinni tartibga keltirish, davlat ishlarida intizom oʻrnatish kabi muhim chora-tadbirlarni amalga oshiradi. Boburning dastlabki siyosiy maqsadi Amir Temur davlatining poytaxti, strategik va geografik jihatdan muhim boʻlgan Samarqandni egallash va Movarounnahrda markazlashgan kuchli davlatni saqlash, mustahkamlash hamda Amir Temur saltanatini qayta tiklashdan iborat edi.',
  jang2:
    'BOBURNING ANDIJONNI QAYTA EGALLASHI . Boburning taxtga chiqishi, 1495-yil Bu paytda, qisqa muddat ichida Samarqand taxtiga uchinchi hukmdor kelgan edi. Sulton Ahmad Mirzo vafoti (1494-yil iyul) dan keyin taxtga oʻtirgan Sulton Mahmud Mirzo Samarqandda davlatni 5-6 oydan ortiq idora etmadi — qisqa muddatli kasallikdan soʻng 43 yoshida vafot etdi. Uning oʻrniga Buxoroda hokim boʻlgan oʻgʻli Boysungʻur oʻtiradi. 1495—1496-yillarda Bobur Samarqandga ikki marta muvaffaqiyatsiz yurish qiladi. 1497-yil kuzida u Samarqand atrofidagi bir qancha joylarni va 7 oylik qamaldan soʻng Samarqandni egallaydi, Boysungʻur Qunduzga qochadi. Shahar qamal tufayli nihoyatda ogʻir kunlarni boshidan kechirmoqda edi. Hatto ekkulik don ham topish mushkul edi. Bobur qoʻshinni taʼminlashda katta qiyinchiliklarga duch keldi. Navkarlaridan ayrimlari Andijon va Axsi tomon qochib ketadilar. Buning ustiga Andijonda qolgan ayrim beklar Boburdan yuz oʻgirib, uning ukasi Jahongir Mirzo tarafiga oʻtadilar. Andijondan koʻngli notinch boʻlgan va iqtisodiy qiyinchiliklarga uchragan, ayni zamonda ogʻir xastalikni boshidan kechirgan Bobur Samarqandni yuz kun idora etgandan soʻng, uni tark etishga qaror qiladi, ammo Xoʻjandga yetganda Andijon ham qoʻldan ketib, muxoliflar ixtiyoriga oʻtganini eshitadi. Boburning Toshkent hokimi, togʻasi Mahmudxon koʻmagida Andijonni qayta egallashga urinishi natija bermaydi. Bu muvaffaqiyatsizlik Bobur qoʻshiniga salbiy taʼsir etib, koʻpchilik bek, navkarlar (700—800 kishi) Boburni tark etadi. Oʻziga sodiq kishilar (200—300) bilan qolgan Bobur maʼlum muddat Xoʻjandda turgach, Toshkentga — Mahmudxon huzuriga kelib, Andijonni qaytarib olish rejasini tuza boshlaydi. Maʼlum muddat oʻtgach, Bobur Xoʻjandga qaytadi, koʻp oʻtmay, Margʻilonni qoʻlga kiritadi hamda Andijonni egallash tadbirlarini koʻradi. Nihoyat, 2 yildan soʻng (1498-yil iyun) uni qayta qoʻlga kiritadi. Bobur ukasi Jahongir Mirzo bilan sulh tuzib, uning ixtiyorida „Xoʻjand suvining Axsi tarafi viloyatlarini…“ qoldiradi, Andijon tarafi viloyatlarini oʻz tasarrufiga oladi.',
  jang3:
    'SAMARQANDNI BOSIB OLISH UCHUN QILINGAN HARAKATLAR . Bobur Samarqandda Temuriylarning oʻzaro urushlari kuchaygan kezlarda Shayboniyxon Movarounnahrni istilo qilishga kirishadi. U 1499-yil Jizzax va Samarqand orqali Qarshi va Shahrisabzgacha bosib boradi, katta oʻlja bilan Dashti Qipchoqqa qaytadi. Oradan koʻp oʻtmay, katta kuch bilan Movarounnahrga qaytgan Shayboniyxon Buxoro va Qorakoʻlni egallaydi (1499-yil), Sulton Ali Mirzo kaltabinlik bilan Samarqandni Shayboniyxonga jangsiz topshiradi (1500-yil), biroq shahar aholisi va zodagonlarining maʼlum qismi temuriylar hukmdorligini tiklash tarafdori edi. Ular Fargʻona hokimi Boburga maktub yoʻllab, Samarqandni ishgʻol qilishga daʼvat etganlar. Bobur 1500-yil kech kuzida oʻz qoʻshini (240 kishi) bilan Samarqandga yetib kelgach, aholi unga peshvoz chiqib, shahar darvozalarini ochib beradi. Shayboniyxonning shahar himoyasi uchun qoldirgan 600 nafar askari qirib tashlanadi. Shayboniyxon Buxoroga chekinadi. Qisqa vaqt ichida Samarqandning barcha tumanlari, Qarshi va Gʻuzor shaharlarida Bobur hokimligi eʼtirof etiladi, ammo shaharda oziq-ovqat zaxiralari tugab, ocharchilik boshlangan edi. Bundan xabar topgan Shayboniyxon katta kuch toʻplab, yana Samarqandga yurish boshlaydi. 1501-yil aprelda Zarafshon boʻyidagi Saripul qishlogʻi yaqinida boʻlgan jangda Bobur qoʻshinlari yengiladi. Bobur Samarqandga chekinadi. Shahar yana qamal qilinib, u toʻrt oy davom etadi. Qamalda qolgan shahar aholisining ochlikdan tinkasi quriydi, Bobur 1501-yilning 2-yarmida noilojlikdan Samarqandni tark etib, Toshkentga, Mahmudxon huzuriga yoʻl oladi.',
  jang4:
    "HINDISTONNI EGALLASHI . Bobur Hindistonda, 1527-yil. 1519-yil bahoriga kelib Bobur Hindistonni zabt etish rejalarini amalga oshirishga kirishadi va keyingi 5-6 yil davomida bir necha yurishlar uyushtiradi. Oʻzbek sultonlari Hamza sulton, Mahdi sulton, Mamaq sulton Bobur qabulidaNihoyat, 1525-yilda Bobur 12 ming qoʻshin bilan Hindistonga yurish boshladi .1526-yil aprelda Panipatda asosiy raqibi, Dehli sultoni Ibrohim Loʻdiyning yuz ming kishilik qoʻshinini 12 minglik askari bilan tor-mor qiladi hamda Dehlini egallaydi.Oradan koʻp oʻtmay, ikkinchi yirik hind sarkardasi Rano Sango ustidan ham zafar qozonib, Shimoliy Hindistonning Bengaliyagacha boʻlgan qismini oʻziga boʻysundiradi.Agrani oʻziga poytaxt sifatida tanlagan Bobur katta qurilish va obodonchilik ishlarini boshlab yuboradi. Shu tariqa Bobur Hindistonda uch yarim asrga yaqin hukm surgan qudratli boburiylar sulolasiga asos soladi.Hindiston ravnaqi uchun qoʼshgan hissasiBobur Hindistonda ham, xuddi Afgʻonistonda boʻlganidek, koʻplab ijtimoiy xayrli ishlarni amalga oshirdi, mamlakat taraqqiyotiga jiddiy taʼsir koʻrsatdi. Tarqoqlik va parokandalikka, oʻzaro ichki nizo, qirgʻinlarga barham berib, viloyatlarni birlashtirdi, markazlashgan davlatni mustahkamlash va yurtni obodonlashtirishga, ilmu hunar va dehqonchilikni rivojlantirishga katta eʼtibor qaratdi. Qurilish ishlariga boshchilik qildi.U turli g'azallar muallifi sanaladi.",
  jang5:
    'KOBULNI EGALLASHI .  Bobur tomonidan Kobulda zarb qilingan tanga, 1507—1508 Bobur jangchilari,1520-yillar Bobur 200-300 kishilik navkari bilan Hisor togʻlari orqali Afgʻonistonga oʻtadi va u yerdagi ichki nizolardan foydalanib Gʻazni va Kobulni egallaydi. Bobur Kobulni egallagach, mustaqil davlat tuzishga jadal kirishadi, qoʻshinni tartibga keltiradi, qattiq ichki intizom oʻrnatadi. Kobulga, umuman Afgʻonistonga Bobur oʻz yurti kabi qaradi, qurilish, obodonlashtirish, kasbu hunar va qishloq xoʻjaligini rivojlantirish ishlarini boshlab yuboradi. „Bogʻi Shaxroro“, „Bogʻi Jahonoro“, „Oʻrtabogʻ“, „Bogʻi vafo“ va „Bogʻi Bobur“ kabi oromgohlar tashkil etdi. Shahar ichidagi Bolo Hisor qalʼasini oʻz qarorgohiga aylantirib, uni qayta taʼmirlatdi, yangi imoratlar qurdirdi va oilasi bilan shu qalʼada yashadi. Uning Humoyun, Gulbadanbegim, Komron va Hindol ismli farzandlari shu yerda tugʻiladi. 1506-yil bahorda vafot etgan Qutlugʻ Nigorxonim Mirzo Ulugʻbek shu yerda bunyod ettirgan „Bogʻi Navroʻziy“ga dafn etiladi. Bobur Afgʻonistonda bir fotih sifatida emas, balki shu yurt, el obodonligi va ravnaqi uchun jon kuydirgan tadbirli hukmron sifatida qizgʻin faoliyat koʻrsatdi, uning manfaatlari yoʻlida odilona va oqilona ish tutdi. Afgʻonistondagi amaliy faoliyatiga koʻra, Bobur butun Xuroson va Movarounnahrda qudratli davlat boshligʻi va muzaffar sarkarda sifatida katta obroʻ orttira bordi, mintaqadagi siyosiy hayot eʼtiborli oʻringa koʻtarildi. Shayboniylarning tobora kuchayib borayotgan yurishiga qarshi birgalikda chora koʻrish masalasida Sulton Husayn Boyqaro barcha temuriy hukmdorlar qatorida Boburni ham maslahat yigʻiniga maxsus taklif etishi ana shunday yuksak nufuzni koʻrsatuvchi dalildir. Bobur shu taklif boʻyicha Hirotga otlanadi. Husayn Boyqaroning toʻsatdan vafot etishiga (1506-yil) qaramay, u Hirotga boradi va temuriy hukmdorlar bilan uchrashib muzokaralar oʻtkazadi. Temuriy hukmdorlarning birlashib Shayboniyxon qoʻshinlariga toʻsiq qoʻyish rejalari amalga oshmaydi va tez orada birin-ketin magʻlubiyatga uchrab, saltanatni batamom qoʻldan chiqaradilar.1507-yil boshlarida Bobur Hindistonga yurish boshlaydi, ammo bu urinishi muvaffaqiyatsiz tugab, yana poytaxt Kobulga qaytadi.',
  lorem1: '1. Movarounnahr taxti uchun kurash 👇',
  lorem2: '2. Boburning Andijonni qayta egallashi 👇',
  lorem3: '3. Samarqandni bosib olish uchun qilingan harakatlar  👇',
  lorem4: '4. Hindistonni egallashi 👇',
  lorem5: '5. Kobulni egallashi  👇',
  not: "Ma'lumot",
  found: "Yo'q",
  subcrib1: 'Bizning xabarnomamizga obuna bo`ling',
  subcrib2: 'E-pochtangizga obuna bo`ling va qiziqishlaringiz asosida yangiliklar byulleteni va qiziqarli yangiliklarga obuna bo`ling',
}

export default translationsUz
